#!/usr/bin/env bash

exists () {
    type "$1" &> /dev/null ;
}

if exists /usr/local/bin/ifstat ; then
	echo "CPU $($(dirname "$0")/osx-cpu-temp) | $(networksetup -getairportnetwork en0 | cut -c 24-) % $(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep -o '\-[0-9]*' | head -n 1)"
else
	echo "DOWN $(networksetup -getairportnetwork en0 | cut -c 24-)"
fi

